# Generated by Django 5.1.2 on 2024-10-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersall',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
