# Generated by Django 5.1.2 on 2024-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog', '0002_alter_usersall_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersall',
            name='private_status',
            field=models.CharField(choices=[('default', 'Default'), ('admin', 'Admin')], default='default', max_length=20),
        ),
    ]
