# Generated by Django 5.1.2 on 2024-10-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog', '0003_usersall_private_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersall',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
